// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/share.tsx";
import * as $$0 from "./islands/Home.tsx";
import * as $$1 from "./islands/RedirectToHome.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/share.tsx": $1,
  },
  islands: {
    "./islands/Home.tsx": $$0,
    "./islands/RedirectToHome.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
